
# ENV vars
env:
    WANDB_PROJECT : nv-reason-cxr  

# Data training arguments
dataset_name: nv-reason-cxr-data
dataset_path: sft.jsonl
dataset_root: datalists/
image_dir: images/
dataset_streaming: true # for streaming, max_steps is required

##########################################################################
# Model arguments
##########################################################################

model_name_or_path: nvidia/NV-Reason-CXR-3B
model_revision: main
torch_dtype: bfloat16
trust_remote_code: false
attn_implementation: flash_attention_2

##########################################################################
# SFT trainer config
##########################################################################

output_dir: data/tmp
overwrite_output_dir: true

num_train_epochs: 2
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

optim: adamw_torch_fused
learning_rate: 2.0e-05 
lr_scheduler_type: cosine
warmup_ratio: 0.03
max_grad_norm: 0.3

do_eval: false 
eval_strategy: "no"

save_steps: 100  
save_total_limit: 3 

bf16: true
tf32: true
use_liger_kernel: true

ddp_find_unused_parameters: false
push_to_hub: false

seed: 123

# run_name: run_name #defaults to output folder name
report_to: wandb
log_level: info
logging_steps: 20  
logging_strategy: steps

#VLM specific
remove_unused_columns: false 
dataset_text_field: ""
dataset_kwargs: {"skip_prepare_dataset": True} 
dataset_num_proc: 4 
max_length: null
